--- create load table 
 create table tb_load
 (   id int
	,nm_name text(500)
    ,dt_load date
    				
 );
 
 select * from tb_load;
 
 --- * create tabela de valores gazolina *---
 drop table t_valores;
 
 create table t_tmp_valores (CNPJ int
						 ,NOME text(100)
                         ,ENDERECO text(500)
                         ,COMPLEMENTO text(500)
                         ,BAIRRO text(500)
                         ,MUNICIPIO text(500)
                         ,UF text(5)
                         ,PRODUTO text(500)
                         ,VALOR_VENDA decimal(2.3)	
                         ,DATA_CADASTRO date
                         ,DATA_CARGA date
                         );
 select * from t_tmp_valores;

 create table if not exists tb_analise_mercado 
            (
                 id                                    text(500)
                ,age                                   text(500)
                ,gender                                text(500)
                ,living_in_brasil                      text(500)
                ,living_state                          text(500)
                ,born_or_graduated                     text(500)
                ,degreee_level                         text(500)
                ,job_situation                         text(500)
                ,workers_number                        text(500)
                ,manager                               text(500)
                ,salary_range                          text(500)
                ,time_experience_data_science          text(500)
                ,time_experience_before                text(500)
                ,is_data_science_professional          text(500)
                ,linear_regression                     text(500)
                ,logistic_regression                   text(500)
                ,glms                                  text(500)
                ,decision_tree                         text(500)
                ,random_forest                         text(500)
                ,neural_networks                       text(500)
                ,bayesian_inference                    text(500)
                ,ensemble                              text(500)
                ,svms                                  text(500)
                ,cnns                                  text(500)
                ,rnns                                  text(500)
                ,hmms                                  text(500)
                ,gans                                  text(500)
                ,markov_chains                         text(500)
                ,nlp                                   text(500)
                ,gradient_boosted_machines             text(500)
                ,cluster_analysis                      text(500)
                ,survival_analysis                     text(500)
                ,longitudinal_data_analysis            text(500)
                ,joint_analysis                        text(500)
                ,no_listed_methods                     text(500)
                ,sql_01                                text(500)
                ,r                                     text(500)
                ,python                                text(500)
                ,c_sharp                               text(500)
                ,dotnet                                text(500)
                ,java                                  text(500)
                ,julia                                 text(500)
                ,sas_stata                             text(500)
                ,visual_basic_vba                      text(500)
                ,scala                                 text(500)
                ,matlab                                text(500)
                ,php                                   text(500)
                ,no_listed_languages                   text(500)
                ,most_used_proggraming_languages       text(500)
                ,sql_02                                text(500)
                ,nosql_01                              text(500)
                ,images                                text(500)
                ,nlp_01                                text(500)
                ,videos                                text(500)
                ,sheets                                text(500)
                ,other_1                               text(500)
                ,sql_03                                text(500)
                ,nosql_02                              text(500)
                ,imagens_02                            text(500)
                ,nlp_02                                text(500)
                ,videos_02                             text(500)
                ,planilhas                             text(500)
                ,other_2                               text(500)
                ,aws                                   text(500)
                ,gcp                                   text(500)
                ,azure                                 text(500)
                ,ibm                                   text(500)
                ,on_premise_servers                    text(500)
                ,cloud_propria                         text(500)
                ,other_3                               text(500)
                ,mysql                                 text(500)
                ,oracle                                text(500)
                ,sql_server                            text(500)
                ,aurora                                text(500)
                ,dynamodb                              text(500)
                ,coachdb                               text(500)
                ,cassandra                             text(500)
                ,mongodb                               text(500)
                ,mariadb                               text(500)
                ,datomic                               text(500)
                ,s3                                    text(500)
                ,postgresql                            text(500)
                ,elaticsearch                          text(500)
                ,db2                                   text(500)
                ,ms_access                             text(500)
                ,sqlite                                text(500)
                ,sybase                                text(500)
                ,firebase                              text(500)
                ,vertica                               text(500)
                ,redis                                 text(500)
                ,neo4j                                 text(500)
                ,google_bigtable                       text(500)
                ,hbase                                 text(500)
                ,other_4                               text(500)
                ,microsoft_powerbi                     text(500)
                ,qlik_view_qlik_sense                  text(500)
                ,tableau                               text(500)
                ,metabase                              text(500)
                ,superset                              text(500)
                ,redash                                text(500)
                ,microstrategy                         text(500)
                ,ibm_analytics_cognos                  text(500)
                ,sap_business_objects                  text(500)
                ,oracle_business_intelligence          text(500)
                ,birst                                 text(500)
                ,looker                                text(500)
                ,google_data_studio                    text(500)
                ,only_excel_gsheets                    text(500)
                ,no_bi_tool_at_work                    text(500)
                ,other_5                               text(500)
                ,sql_stored_procedures                 text(500)
                ,apache_airflow                        text(500)
                ,luigi                                 text(500)
                ,aws_glue                              text(500)
                ,talend                                text(500)
                ,pentaho                               text(500)
                ,alteryx                               text(500)
                ,oracle_data_integrator                text(500)
                ,ibm_data_stage                        text(500)
                ,sap_bw_etl                            text(500)
                ,siss_sql_server_integration_services  text(500)
                ,other_6                               text(500)
                ,have_data_warehouse                   text(500)
                ,google_bigquery                       text(500)
                ,aws_redshift                          text(500)
                ,snowflake                             text(500)
                ,oracle_02                             text(500)
                ,postgres_mysql                        text(500)
                ,ibm_02                                text(500)
                ,teradata                              text(500)
                ,microsoft_azure                       text(500)
                ,do_not_know                           text(500)
                ,other_7                               text(500)
                ,data_hackers_blog                     text(500)
                ,data_hackers_podcast                  text(500)
                ,weekly_newsletter                     text(500)
                ,slack_channel                         text(500)
                ,data_hackers_bootcamp                 text(500)
                ,do_not_know_data_hackers              text(500)
                ,prefered_data_hackers_initiative      text(500)
                ,telegram_groups                       text(500)
                ,whatsapp_groups                       text(500)
                ,youtube_channels                      text(500)
                ,other_brasilian_blogs                 text(500)
                ,other_slack_channels                  text(500)
                ,twitter                               text(500)
                ,abroad_blogs                          text(500)
                ,abroad_podcasts                       text(500)
                ,meetups_and_events                    text(500)
                ,only_data_hackers                     text(500)
                ,other_8                               text(500)
                ,udacity                               text(500)
                ,coursera                              text(500)
                ,udemy                                 text(500)
                ,height                                text(500)
                ,edx                                   text(500)
                ,data_camp                             text(500)
                ,data_quest                            text(500)
                ,kaggle_learn                          text(500)
                ,online_courses                        text(500)
                ,other_9                               text(500)
                ,data_science_plataforms_preference    text(500)
                ,other_10                              text(500)
                ,draw_participation                    text(500)
                ,living_macroregion                    text(500)
                ,origin_macroregion                    text(500)
                ,anonymized_degree_area                text(500)
                ,anonymized_market_sector              text(500)
                ,anonymized_manager_level              text(500)
                ,anonymized_role                       text(500)

            );
-- sensores IOT
create table if not exists tb_sensor_IOT
(
   ambient_temperature float 
   ,datetime           datetime
   ,humidity           float 
   ,lat                float 
   ,lng                float 
   ,photo_sensor       float 
   ,radiation_level    int 
   ,sensor_id          text 
   ,sensor_name        text 
   ,sensor_uuid        text 
   ,timestamp          timestamp 
)